#LEVEL 3
# 1. Sliding Window Maximum (advanced)
# 2. Word Ladder II (BFS + DFS + Backtracking)
# 3. Shortest Path in a Grid with Obstacles Elimination (BFS + DP)
# 4. Minimum Window Subsequence (DP + Two Pointers)
# 5. Maximum Rectangle (Stack + DP)
# 6. Merge k Sorted Lists (Heap + Divide & Conquer)
# 7. Regular Expression Matching (DP)
# 8. Wildcard Matching (DP)
# 9. Maximum XOR of Two Numbers in an Array (Trie + Bitmask)
# 10. Traveling Salesman Problem (Bitmask DP)
# 11. Minimum Cost to Connect All Points (MST + Graph)
# 12. Shortest Path to Get All Keys (BFS + Bitmask)
# 13. Minimum Number of Refueling Stops (Greedy + Heap)
# 14. Minimum Swaps to Make Sequences Increasing (DP + Greedy)
# 15. Minimum Cost to Merge Stones (DP + Greedy)
# 16. Optimal Binary Search Tree (DP)
# 17. Find the Shortest Superstring (DP + Bitmask)
# 18. Maximum Profit in Job Scheduling (DP + Binary Search)
#LEVEL 3