#LEVEL 1
# 1. Two Sum (Hashing pattern)
# 2. Valid Parentheses (Stack pattern)
# 3. Reverse Linked List (Linked List pattern)
# 4. Merge Two Sorted Lists (Linked List pattern)
# 5. Valid Palindrome (Two Pointer pattern)
# 6. Remove Duplicates from Sorted Array (Two Pointer)
# 7. Move Zeroes (Two Pointer)
# 8. Best Time to Buy and Sell Stock (One-pass pattern)
# 9. Contains Duplicate (Hashing)
# 10. Intersection of Two Arrays (Hashing)
# 11. Min Stack (Stack pattern)
# 12. Valid Anagram (Hashing)
# 13. Pascal’s Triangle (DP pattern)
# 14. Maximum Depth of Binary Tree (DFS pattern)
# 15. Symmetric Tree (BFS/DFS pattern)
# 16. Merge Intervals (Sorting + Greedy)
# 17. Group Anagrams (Hashing pattern)
# 18. Find Pivot Index (Prefix Sum pattern)
#LEVEL 1