#LEVEL 3
# 1. Merge k Sorted Lists (optimized using heap)
# 2. Reverse Nodes in k-Group (harder)
# 3. Split Linked List in Parts (optimized)
# 4. Copy List with Random Pointer (optimized)
# 5. Reverse Linked List II (optimized)
# 6. Sort List (optimized merge sort)
# 7. LRU Cache (linked list + hash map)
# 8. Design Skiplist (linked list + levels)
# 9. Add Two Numbers (advanced follow-up)
# 10. Linked List Cycle II (optimized)
# 11. Flatten a Multilevel Doubly Linked List (optimized)
# 12. Reverse Nodes in k-Group (advanced)
# 13. Copy List with Random Pointer (advanced)
# 14. Merge k Sorted Lists (advanced)
# 15. Odd Even Linked List (advanced)
# 16. Reorder List (optimized)
# 17. Partition List (optimized)
# 18. Rotate List (optimized)
#LEVEL 3