# Generated by Django 6.0 on 2026-01-25 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('notable_effects', models.JSONField(default=list, help_text="List of effects e.g. ['Hydrating', 'Anti-aging']")),
                ('skin_type', models.JSONField(default=list, help_text="List of skin types e.g. ['Oily', 'Sensitive']")),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('picture_src', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
    ]
